/**
 * `agentspec generate-policy <file>`
 *
 * Reads an agent.yaml manifest and emits an OPA Rego policy bundle:
 *   - policy.rego  — per-agent deny rules derived from manifest declarations
 *   - data.json    — baseline thresholds (toxicity, TTL, cost limits, ...)
 *
 * The bundle can be loaded by OPA directly:
 *   opa run --server --bundle <outputDir>
 *
 * This implements Layer 2 of the OPA integration: the manifest → Rego translator.
 * Framework sub-SDKs (sdk-langgraph, sdk-crewai, …) emit the runtime input that
 * these rules evaluate against.
 */

import { Command } from 'commander'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { loadManifest, type AgentSpecManifest } from '@agentspec/sdk'
import { printError, printHeader } from '../utils/output.js'

// ── Public types ───────────────────────────────────────────────────────────────

export interface PolicyDataJson {
  toxicityThreshold?: number
  hallucinationThreshold?: number
  shortTermTtlSeconds?: number
  maxMonthlyUSD?: number
  alertAtUSD?: number
  /** Tool names where destructiveHint === true */
  destructiveTools: string[]
  piiScrubFields?: string[]
  blockedTopics?: string[]
}

export interface PolicyGenerationResult {
  agentName: string
  outputDir: string
  files: string[]
  rulesGenerated: number
}

// ── Rego generator ─────────────────────────────────────────────────────────────

/**
 * Pure function — generates a Rego policy document from an AgentSpec manifest.
 *
 * Each manifest declaration becomes a `deny contains "…" if {…}` rule.
 * The caller is responsible for writing the result to disk.
 */
/**
 * Sanitize an agent name for use as a Rego package identifier.
 *
 * Rego package path segments must be valid identifiers: [a-zA-Z_][a-zA-Z0-9_]*
 * Agent names (metadata.name) are lowercase slugs that may contain hyphens.
 * We replace hyphens with underscores so the package name is valid Rego.
 *
 * Example: "fitness-tracker" → "fitness_tracker"
 * OPA query path: /v1/data/agentspec/agent/fitness_tracker/deny
 */
export function sanitizePackageName(name: string): string {
  return name.replace(/-/g, '_')
}

export function generateRegoPolicy(manifest: AgentSpecManifest): string {
  const agentName = manifest.metadata.name
  const packageName = sanitizePackageName(agentName)
  const spec = manifest.spec
  const lines: string[] = []

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# Generated by agentspec generate-policy`)
  lines.push(`# Agent: ${agentName}`)
  lines.push(`# Generated: ${new Date().toISOString()}`)
  lines.push(`#`)
  lines.push(`# OPA evaluates this policy on every LLM request forwarded by the`)
  lines.push(`# framework sub-SDK (sdk-langgraph, sdk-crewai, …).`)
  lines.push(`# Only deny rules relevant to this agent's manifest declarations are included.`)
  lines.push(`#`)
  lines.push(`# OPA query: POST /v1/data/agentspec/agent/${packageName}/deny`)
  lines.push(``)
  lines.push(`package agentspec.agent.${packageName}`)
  lines.push(``)
  lines.push(`import rego.v1`)
  lines.push(``)
  lines.push(`default allow := false`)
  lines.push(``)
  lines.push(`allow if {`)
  lines.push(`    count(deny) == 0`)
  lines.push(`}`)
  lines.push(``)

  // ── Input guardrail enforcement ──────────────────────────────────────────────
  const inputGuardrails = spec.guardrails?.input ?? []
  if (inputGuardrails.length > 0) {
    lines.push(`# ── Input guardrail enforcement ─────────────────────────────────────────────`)
    lines.push(`# Each declared input guardrail MUST appear in input.guardrails_invoked.`)
    lines.push(`# The framework sub-SDK is responsible for populating that list.`)
    lines.push(``)
    for (const g of inputGuardrails) {
      const ruleId = g.type.replace(/-/g, '_') + '_not_invoked'
      lines.push(`deny contains "${ruleId}" if {`)
      lines.push(`    input.request_type == "llm_call"`)
      lines.push(`    not "${g.type}" in input.guardrails_invoked`)
      lines.push(`}`)
      lines.push(``)
    }
  }

  // ── Output guardrail enforcement ─────────────────────────────────────────────
  const outputGuardrails = spec.guardrails?.output ?? []
  if (outputGuardrails.length > 0) {
    lines.push(`# ── Output guardrail enforcement ────────────────────────────────────────────`)
    lines.push(``)
    for (const g of outputGuardrails) {
      if (g.type === 'toxicity-filter') {
        lines.push(`deny contains "toxicity_threshold_exceeded" if {`)
        lines.push(`    input.request_type == "llm_call"`)
        lines.push(`    input.toxicity_score >= data.toxicityThreshold`)
        lines.push(`}`)
        lines.push(``)
      } else if (g.type === 'hallucination-detector') {
        lines.push(`deny contains "hallucination_threshold_exceeded" if {`)
        lines.push(`    input.request_type == "llm_call"`)
        lines.push(`    input.hallucination_score >= data.hallucinationThreshold`)
        lines.push(`}`)
        lines.push(``)
      }
    }
  }

  // ── Cost control enforcement ─────────────────────────────────────────────────
  if (spec.model.costControls?.maxMonthlyUSD !== undefined) {
    lines.push(`# ── Cost control enforcement ────────────────────────────────────────────────`)
    lines.push(`# Monthly cost projected from daily spend × 30.`)
    lines.push(``)
    lines.push(`deny contains "monthly_cost_limit_exceeded" if {`)
    lines.push(`    input.request_type == "llm_call"`)
    lines.push(`    input.cost_today_usd * 30 > data.maxMonthlyUSD`)
    lines.push(`}`)
    lines.push(``)
  }

  // ── Memory TTL enforcement ───────────────────────────────────────────────────
  const ttlSeconds = spec.memory?.shortTerm?.ttlSeconds
  if (ttlSeconds !== undefined) {
    lines.push(`# ── Memory TTL enforcement ──────────────────────────────────────────────────`)
    lines.push(`# Memory writes must use the declared TTL exactly.`)
    lines.push(``)
    lines.push(`deny contains "memory_ttl_mismatch" if {`)
    lines.push(`    input.memory_write.ttl_seconds != data.shortTermTtlSeconds`)
    lines.push(`}`)
    lines.push(``)
  }

  // ── Destructive tool confirmation ─────────────────────────────────────────────
  const destructiveTools = (spec.tools ?? [])
    .filter((t) => t.annotations?.destructiveHint === true)
    .map((t) => t.name)

  if (destructiveTools.length > 0) {
    lines.push(`# ── Destructive tool confirmation ───────────────────────────────────────────`)
    lines.push(`# Tools annotated destructiveHint=true require explicit user confirmation.`)
    lines.push(``)
    lines.push(`deny contains "destructive_tool_without_confirmation" if {`)
    lines.push(`    some tool in input.tools_called`)
    lines.push(`    tool in data.destructiveTools`)
    lines.push(`    not input.user_confirmed`)
    lines.push(`}`)
    lines.push(``)
  }

  return lines.join('\n')
}

// ── Data JSON generator ────────────────────────────────────────────────────────

/**
 * Pure function — extracts thresholds and configuration from the manifest
 * into the OPA `data` document.
 *
 * OPA evaluates `data.*` references in policy.rego against this document.
 */
export function generateDataJson(manifest: AgentSpecManifest): PolicyDataJson {
  const spec = manifest.spec
  const data: PolicyDataJson = {
    destructiveTools: [],
  }

  // Toxicity threshold from output guardrail
  const toxicityGuardrail = (spec.guardrails?.output ?? []).find(
    (g) => g.type === 'toxicity-filter',
  )
  if (toxicityGuardrail && 'threshold' in toxicityGuardrail) {
    data.toxicityThreshold = toxicityGuardrail.threshold
  }

  // Hallucination threshold from output guardrail
  const hallucinationGuardrail = (spec.guardrails?.output ?? []).find(
    (g) => g.type === 'hallucination-detector',
  )
  if (hallucinationGuardrail && 'threshold' in hallucinationGuardrail) {
    data.hallucinationThreshold = hallucinationGuardrail.threshold
  }

  // Memory short-term TTL
  if (spec.memory?.shortTerm?.ttlSeconds !== undefined) {
    data.shortTermTtlSeconds = spec.memory.shortTerm.ttlSeconds
  }

  // Cost controls
  if (spec.model.costControls?.maxMonthlyUSD !== undefined) {
    data.maxMonthlyUSD = spec.model.costControls.maxMonthlyUSD
  }
  if (spec.model.costControls?.alertAtUSD !== undefined) {
    data.alertAtUSD = spec.model.costControls.alertAtUSD
  }

  // Destructive tools
  data.destructiveTools = (spec.tools ?? [])
    .filter((t) => t.annotations?.destructiveHint === true)
    .map((t) => t.name)

  // PII scrub fields from memory hygiene
  if (spec.memory?.hygiene?.piiScrubFields?.length) {
    data.piiScrubFields = [...spec.memory.hygiene.piiScrubFields]
  }

  // Blocked topics from topic-filter input guardrail
  const topicFilter = (spec.guardrails?.input ?? []).find((g) => g.type === 'topic-filter')
  if (topicFilter && 'blockedTopics' in topicFilter) {
    data.blockedTopics = [...topicFilter.blockedTopics]
  }

  return data
}

// ── Commander registration ─────────────────────────────────────────────────────

export function registerGeneratePolicyCommand(program: Command): void {
  program
    .command('generate-policy <file>')
    .description(
      'Generate OPA Rego policy bundle from agent.yaml declarations',
    )
    .option('--out <dir>', 'Output directory for generated policy files')
    .option('--json', 'Output generation summary as JSON')
    .action(
      async (
        file: string,
        opts: { out?: string; json?: boolean },
      ) => {
        // Load manifest (resolve: false — no I/O for $env/$file refs)
        let manifest: AgentSpecManifest
        try {
          const result = loadManifest(file, { resolve: false })
          manifest = result.manifest
        } catch (err) {
          printError(`Cannot load manifest: ${String(err)}`)
          process.exit(1)
        }

        const agentName = manifest.metadata.name
        const outputDir = resolve(opts.out ?? join('policies', agentName))

        // Generate policy files (pure — no I/O yet)
        const rego = generateRegoPolicy(manifest)
        const dataJson = generateDataJson(manifest)

        // Count deny rules as a proxy for "rules generated"
        const rulesGenerated = (rego.match(/^deny contains/gm) ?? []).length

        // Write files
        mkdirSync(outputDir, { recursive: true })
        const regoPath = join(outputDir, 'policy.rego')
        const dataPath = join(outputDir, 'data.json')
        writeFileSync(regoPath, rego, 'utf-8')
        writeFileSync(dataPath, JSON.stringify(dataJson, null, 2), 'utf-8')

        const result: PolicyGenerationResult = {
          agentName,
          outputDir,
          files: ['policy.rego', 'data.json'],
          rulesGenerated,
        }

        if (opts.json) {
          console.log(JSON.stringify(result, null, 2))
          return
        }

        // Human-readable output
        printHeader(`AgentSpec Generate Policy — ${agentName}`)
        console.log(`  Output  : ${outputDir}`)
        console.log(`  Files   : policy.rego, data.json`)
        console.log(`  Rules   : ${rulesGenerated} deny rules generated`)
        console.log()
        console.log(`  To serve with OPA:`)
        console.log(`    opa run --server --bundle ${outputDir}`)
        console.log()
      },
    )
}
