/**
 * @agentspec/adapter-langgraph
 *
 * Generates LangGraph (Python) agent code from an AgentSpec manifest.
 * Auto-registers with the @agentspec/sdk adapter registry on import.
 *
 * Usage:
 *   import '@agentspec/adapter-langgraph'  // side-effect import — registers the adapter
 *   generateAdapter(manifest, 'langgraph')
 */

import {
  registerAdapter,
  type FrameworkAdapter,
  type GeneratedAgent,
  type AgentSpecManifest,
} from '@agentspec/sdk'

import { generateAgentPy } from './generators/agent-py.js'
import { generateRequirementsTxt } from './generators/requirements-txt.js'
import { generateEnvExample } from './generators/env-example.js'
import { generateGuardrailsPy } from './generators/guardrails-py.js'

export interface LangGraphAdapterOptions {
  /** Include Dockerfile in output. Default: false */
  includeDockerfile?: boolean
  /** Include a simple FastAPI server wrapper. Default: false */
  includeApiServer?: boolean
}

const langGraphAdapter: FrameworkAdapter<LangGraphAdapterOptions> = {
  framework: 'langgraph',
  version: '0.1.0',

  generate(
    manifest: AgentSpecManifest,
    options: LangGraphAdapterOptions = {},
  ): GeneratedAgent {
    const files: Record<string, string> = {}

    // Core agent file
    files['agent.py'] = generateAgentPy(manifest)

    // Requirements
    files['requirements.txt'] = generateRequirementsTxt(manifest)

    // .env.example
    files['.env.example'] = generateEnvExample(manifest)

    // Guardrails (if configured)
    const guardrailsPy = generateGuardrailsPy(manifest)
    if (guardrailsPy) {
      files['guardrails.py'] = guardrailsPy
    }

    // Dockerfile
    if (options.includeDockerfile) {
      files['Dockerfile'] = generateDockerfile(manifest)
    }

    // FastAPI server wrapper
    if (options.includeApiServer) {
      files['server.py'] = generateServerPy(manifest)
    }

    // README
    files['README.md'] = generateReadme(manifest)

    // Collect all env vars referenced
    const envVars = [...(manifest.spec.requires?.envVars ?? [])]

    const installCommands = [
      'python -m venv .venv',
      'source .venv/bin/activate  # or .venv\\Scripts\\activate on Windows',
      'pip install -r requirements.txt',
      'cp .env.example .env && vim .env',
    ]

    return {
      framework: 'langgraph',
      files,
      installCommands,
      envVars,
      readme: files['README.md']!,
    }
  },
}

// ── Auto-register on import ───────────────────────────────────────────────────
registerAdapter(langGraphAdapter)

// ── Re-export adapter for introspection ──────────────────────────────────────
export { langGraphAdapter }

// ── Helper generators ─────────────────────────────────────────────────────────

function generateDockerfile(manifest: AgentSpecManifest): string {
  return `FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "agent.py"]
`
}

function generateServerPy(manifest: AgentSpecManifest): string {
  const { metadata, spec } = manifest
  const port = spec.api?.port ?? 8000
  const prefix = spec.api?.pathPrefix ?? '/api/v1'

  return `"""
FastAPI server for ${metadata.name}
Generated by AgentSpec

Run: uvicorn server:app --reload --port ${port}
"""

import os
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from agent import run_agent

app = FastAPI(
    title="${metadata.name}",
    description="${metadata.description}",
    version="${metadata.version}",
)


class ChatRequest(BaseModel):
    message: str
    thread_id: str = "default"


class ChatResponse(BaseModel):
    response: str
    thread_id: str


@app.get("${prefix}/health")
async def health():
    return {"status": "healthy", "agent": "${metadata.name}"}


@app.post("${prefix}/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    try:
        response = run_agent(request.message, thread_id=request.thread_id)
        return ChatResponse(response=response, thread_id=request.thread_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=${port})
`
}

function generateReadme(manifest: AgentSpecManifest): string {
  const { metadata, spec } = manifest
  const tools = spec.tools ?? []

  return `# ${metadata.name}

${metadata.description}

**Generated by [AgentSpec](https://agentspec.io) v${metadata.version}**

## Stack

| Component | Value |
|-----------|-------|
| Framework | LangGraph |
| Model | ${spec.model.provider}/${spec.model.id} |
| Memory | ${spec.memory?.shortTerm?.backend ?? 'none'} |
| Tracing | ${spec.observability?.tracing?.backend ?? 'none'} |
| Tools | ${tools.length} |

## Quick Start

\`\`\`bash
# 1. Create virtual environment
python -m venv .venv
source .venv/bin/activate

# 2. Install dependencies
pip install -r requirements.txt

# 3. Configure environment
cp .env.example .env
# Edit .env with your API keys

# 4. Run the agent
python agent.py "Hello, what can you help me with?"
\`\`\`

## Tools

${tools.length === 0 ? 'No tools configured.' : tools.map((t) => `- **${t.name}**: ${t.description}`).join('\n')}

## Environment Variables

${(manifest.spec.requires?.envVars ?? []).map((v) => `- \`${v}\``).join('\n')}

## Compliance

Run \`npx agentspec audit agent.yaml\` to check compliance score.

## License

${metadata.license ?? 'MIT'}
`
}
