import type { AgentSpecManifest } from '@agentspec/sdk'

/**
 * Escape a string for safe embedding in a Python double-quoted string literal.
 * Prevents code injection when manifest values are interpolated into generated Python.
 */
function escapePythonString(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
}

/**
 * Resolve a model API key reference to a safe Python expression.
 * Never embeds literal key values — always generates an os.environ.get() call.
 */
function resolveApiKeyExpr(apiKey: string): string {
  if (apiKey.startsWith('$env:')) {
    const varName = apiKey.slice('$env:'.length)
    return `os.environ.get("${escapePythonString(varName)}")`
  }
  if (apiKey.startsWith('$secret:')) {
    const secretName = apiKey.slice('$secret:'.length)
    const envKey = `AGENTSPEC_SECRET_${secretName.toUpperCase().replace(/-/g, '_')}`
    return `os.environ.get("${escapePythonString(envKey)}")`
  }
  // Literal key: NEVER embed it — generate a safe env var reference with a warning comment
  return `os.environ.get("API_KEY")  # WARNING: configure via environment variable — do not hardcode`
}

/**
 * Module-level class map: LangChain package name → class name.
 * Centralised to avoid duplication (fixes DRY violation).
 */
const LANGCHAIN_CLASS_MAP: Record<string, string> = {
  langchain_openai: 'ChatOpenAI',
  langchain_anthropic: 'ChatAnthropic',
  langchain_groq: 'ChatGroq',
  langchain_google_genai: 'ChatGoogleGenerativeAI',
  langchain_mistralai: 'ChatMistralAI',
}

/**
 * Generate the main agent.py file for LangGraph.
 * Produces a ReAct-style agent with tool calling.
 */
export function generateAgentPy(manifest: AgentSpecManifest): string {
  const { metadata, spec } = manifest
  const tools = spec.tools ?? []
  const hasMemory = !!spec.memory?.shortTerm
  const hasObservability = !!spec.observability?.tracing
  const hasFallback = !!spec.model.fallback

  const toolImports = tools
    .map((t) => {
      const funcName = t.function ?? t.name.replace(/-/g, '_')
      return `from tools import ${funcName}`
    })
    .join('\n')

  const toolNames = tools
    .map((t) => t.function ?? t.name.replace(/-/g, '_'))
    .join(', ')

  const modelProvider = mapProvider(spec.model.provider)
  const fallbackProvider = hasFallback ? mapProvider(spec.model.fallback!.provider) : null

  const observabilitySetup = hasObservability
    ? generateObservabilitySetup(spec.observability!)
    : ''

  const memorySetup = hasMemory ? generateMemorySetup(spec.memory!) : ''

  const guardrailImports = spec.guardrails
    ? 'from guardrails import run_input_guardrails, run_output_guardrails'
    : ''

  // Escape all manifest values that flow into Python string literals to prevent code injection
  const safeName = escapePythonString(metadata.name)
  const safeVersion = escapePythonString(metadata.version)
  const safeProvider = escapePythonString(spec.model.provider)
  const safeModelId = escapePythonString(spec.model.id)
  const safeFallbackPrompt = escapePythonString(
    spec.prompts.fallback ?? 'You are a helpful assistant.',
  )
  const safePromptPath = escapePythonString(getRelativePromptPath(spec.prompts.system))

  return `"""
${safeName} — LangGraph Agent
Generated by AgentSpec v${safeVersion}

Model   : ${safeProvider}/${safeModelId}
Tools   : ${tools.length}
Memory  : ${hasMemory ? 'enabled' : 'disabled'}
Tracing : ${hasObservability ? (spec.observability?.tracing?.backend ?? 'none') : 'disabled'}
"""

import os
from typing import Annotated, TypedDict, Sequence
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage
from langchain_core.tools import BaseTool
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
${toolImports ? toolImports + '\n' : ''}${guardrailImports ? guardrailImports + '\n' : ''}
${generateModelImport(modelProvider)}
${hasFallback ? generateFallbackImport(fallbackProvider!) : ''}
${observabilitySetup}
${memorySetup}

# ── System prompt ─────────────────────────────────────────────────────────────

SYSTEM_PROMPT_PATH = os.path.join(os.path.dirname(__file__), "${safePromptPath}")

def load_system_prompt() -> str:
    try:
        with open(SYSTEM_PROMPT_PATH, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "${safeFallbackPrompt}"


SYSTEM_PROMPT = load_system_prompt()

# ── Agent state ───────────────────────────────────────────────────────────────

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], "The conversation messages"]

# ── Tools ─────────────────────────────────────────────────────────────────────

tools: list[BaseTool] = [${toolNames}]

# ── Model setup ───────────────────────────────────────────────────────────────

${generateModelSetup(spec.model, hasFallback)}

# ── Agent graph ───────────────────────────────────────────────────────────────

def call_model(state: AgentState) -> dict:
    """Invoke the LLM with the current conversation state."""
    messages = [SystemMessage(content=SYSTEM_PROMPT)] + list(state["messages"])
${spec.guardrails?.input ? generateInputGuardrailCall() : ''}
    response = llm_with_tools.invoke(messages)
${spec.guardrails?.output ? generateOutputGuardrailCall() : ''}
    return {"messages": [response]}


def should_continue(state: AgentState) -> str:
    """Route to tools or end based on LLM response."""
    last = state["messages"][-1]
    if hasattr(last, "tool_calls") and last.tool_calls:
        return "tools"
    return END


tool_node = ToolNode(tools)

workflow = StateGraph(AgentState)
workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)
workflow.set_entry_point("agent")
workflow.add_conditional_edges("agent", should_continue)
workflow.add_edge("tools", "agent")

${hasMemory ? generateMemoryCompile() : 'graph = workflow.compile()'}

# ── Entry point ───────────────────────────────────────────────────────────────

def run_agent(user_input: str, thread_id: str = "default") -> str:
    """Run the agent with a user message and return the response."""
    config = {"configurable": {"thread_id": thread_id}}
    result = graph.invoke(
        {"messages": [HumanMessage(content=user_input)]},
        config=config,
    )
    return result["messages"][-1].content


if __name__ == "__main__":
    import sys
    prompt = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Hello"
    print(run_agent(prompt))
`
}

function getRelativePromptPath(systemPrompt: string): string {
  if (systemPrompt.startsWith('$file:')) {
    return systemPrompt.slice('$file:'.length)
  }
  return 'prompts/system.md'
}

function mapProvider(provider: string): string {
  const map: Record<string, string> = {
    openai: 'langchain_openai',
    anthropic: 'langchain_anthropic',
    groq: 'langchain_groq',
    google: 'langchain_google_genai',
    azure: 'langchain_openai',
    mistral: 'langchain_mistralai',
    together: 'langchain_together',
    fireworks: 'langchain_fireworks',
    cohere: 'langchain_cohere',
  }
  return map[provider.toLowerCase()] ?? 'langchain_openai'
}

function generateModelImport(pkg: string): string {
  const cls = LANGCHAIN_CLASS_MAP[pkg] ?? 'ChatOpenAI'
  return `from ${pkg} import ${cls}`
}

function generateFallbackImport(pkg: string): string {
  const cls = LANGCHAIN_CLASS_MAP[pkg] ?? 'ChatOpenAI'
  return `from ${pkg} import ${cls} as FallbackModel`
}

function generateModelSetup(model: AgentSpecManifest['spec']['model'], hasFallback: boolean): string {
  const params = model.parameters ?? {}
  const providerPkg = mapProvider(model.provider)
  const cls = LANGCHAIN_CLASS_MAP[providerPkg] ?? 'ChatOpenAI'

  // Never embed literal key values — always generate env var lookups (CRITICAL-3)
  const apiKeyRef = resolveApiKeyExpr(model.apiKey)

  const paramLines = [
    `    model="${escapePythonString(model.id)}"`,
    params.temperature !== undefined ? `    temperature=${params.temperature}` : null,
    params.maxTokens !== undefined ? `    max_tokens=${params.maxTokens}` : null,
    `    api_key=${apiKeyRef}`,
  ]
    .filter(Boolean)
    .join(',\n')

  let setup = `primary_llm = ${cls}(\n${paramLines}\n)\n`

  if (hasFallback) {
    const fb = model.fallback!
    const fbApiKeyRef = resolveApiKeyExpr(fb.apiKey)
    const fbPkg = mapProvider(fb.provider)
    const fbCls = LANGCHAIN_CLASS_MAP[fbPkg] ?? 'ChatOpenAI'

    setup += `
fallback_llm = FallbackModel(
    model="${escapePythonString(fb.id)}",
    api_key=${fbApiKeyRef}
)

# Use primary LLM with automatic fallback on failure
from langchain_core.runnables import RunnableWithFallbacks
llm = primary_llm.with_fallbacks([fallback_llm])
`
  } else {
    setup += '\nllm = primary_llm\n'
  }

  setup += '\n# Bind tools to the model\nllm_with_tools = llm.bind_tools(tools)'
  return setup
}

function generateObservabilitySetup(obs: NonNullable<AgentSpecManifest['spec']['observability']>): string {
  if (!obs.tracing) return ''

  switch (obs.tracing.backend) {
    case 'langfuse':
      return `
# ── Langfuse observability ────────────────────────────────────────────────────
from langfuse.callback import CallbackHandler as LangfuseCallback
langfuse_callback = LangfuseCallback(
    public_key=os.environ.get("LANGFUSE_PUBLIC_KEY"),
    secret_key=os.environ.get("LANGFUSE_SECRET_KEY"),
    host=os.environ.get("LANGFUSE_HOST", "https://cloud.langfuse.com"),
)`
    case 'langsmith':
      return `
# ── LangSmith observability ───────────────────────────────────────────────────
os.environ.setdefault("LANGCHAIN_TRACING_V2", "true")
os.environ.setdefault("LANGCHAIN_PROJECT", "${obs.metrics?.serviceName ?? 'agent'}")`
    default:
      return ''
  }
}

function generateMemorySetup(memory: NonNullable<AgentSpecManifest['spec']['memory']>): string {
  if (!memory.shortTerm) return ''

  switch (memory.shortTerm.backend) {
    case 'redis':
      return `
# ── Redis memory ──────────────────────────────────────────────────────────────
from langgraph.checkpoint.redis import RedisSaver
redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379")
memory_saver = RedisSaver.from_conn_string(redis_url)`
    case 'sqlite':
      return `
# ── SQLite memory ─────────────────────────────────────────────────────────────
from langgraph.checkpoint.sqlite import SqliteSaver
import sqlite3
conn = sqlite3.connect("checkpoints.db", check_same_thread=False)
memory_saver = SqliteSaver(conn)`
    case 'in-memory':
    default:
      return `
# ── In-memory checkpointer ────────────────────────────────────────────────────
from langgraph.checkpoint.memory import MemorySaver
memory_saver = MemorySaver()`
  }
}

function generateMemoryCompile(): string {
  return `graph = workflow.compile(checkpointer=memory_saver)`
}

function generateInputGuardrailCall(): string {
  return `
    # Run input guardrails
    last_user = next((m for m in reversed(list(state["messages"])) if isinstance(m, HumanMessage)), None)
    if last_user:
        run_input_guardrails(last_user.content)
`
}

function generateOutputGuardrailCall(): string {
  return `
    # Run output guardrails
    run_output_guardrails(response.content)
`
}
