import type { AgentSpecManifest } from '@agentspec/sdk'
import { collectEnvRefs } from '@agentspec/sdk'

export function generateEnvExample(manifest: AgentSpecManifest): string {
  const envRefs = collectEnvRefs(manifest)
  const declared = manifest.spec.requires?.envVars ?? []
  const allVars = new Set([...envRefs, ...declared])

  const lines = ['# Generated by AgentSpec — fill in your values', '']

  for (const v of [...allVars].sort()) {
    lines.push(`${v}=`)
  }

  return lines.join('\n') + '\n'
}
