import type { AgentSpecManifest } from '@agentspec/sdk'

export function generateGuardrailsPy(manifest: AgentSpecManifest): string | null {
  const guardrails = manifest.spec.guardrails
  if (!guardrails?.input?.length && !guardrails?.output?.length) return null

  const inputGuardrails = guardrails.input ?? []
  const outputGuardrails = guardrails.output ?? []

  return `"""
Guardrails for ${manifest.metadata.name}
Generated by AgentSpec

Customize the guardrail logic below.
"""

from typing import Optional


class GuardrailError(Exception):
    """Raised when a guardrail rejects a message."""
    pass


# ── Input guardrails ──────────────────────────────────────────────────────────

BLOCKED_TOPICS = [
${inputGuardrails
  .filter((g) => g.type === 'topic-filter')
  .flatMap((g) => (g.type === 'topic-filter' ? g.blockedTopics : []))
  .map((t) => `    "${t}",`)
  .join('\n')}
]


def check_topic_filter(text: str) -> Optional[str]:
    """Check if message contains blocked topics."""
    text_lower = text.lower()
    for topic in BLOCKED_TOPICS:
        if topic.replace("_", " ") in text_lower or topic in text_lower:
            return f"Message contains blocked topic: {topic}"
    return None


def run_input_guardrails(text: str) -> None:
    """Run all input guardrails. Raises GuardrailError if rejected."""
${inputGuardrails.map((g) => generateInputGuardrailCode(g)).join('\n')}
    # All guardrails passed


# ── Output guardrails ─────────────────────────────────────────────────────────

def run_output_guardrails(text: str) -> None:
    """Run all output guardrails. Raises GuardrailError if rejected."""
${outputGuardrails.map((g) => generateOutputGuardrailCode(g)).join('\n')}
    # All guardrails passed
`
}

function generateInputGuardrailCode(g: { type: string }): string {
  switch (g.type) {
    case 'topic-filter':
      return `    violation = check_topic_filter(text)
    if violation:
        raise GuardrailError(violation)`
    case 'prompt-injection':
      return `    # TODO: integrate a prompt injection detection library
    # e.g., from rebuff import Rebuff
    pass`
    case 'pii-detector':
      return `    # TODO: integrate a PII detection library (e.g. Presidio)
    pass`
    default:
      return `    # Custom guardrail: ${g.type}
    pass`
  }
}

function generateOutputGuardrailCode(g: { type: string; threshold?: number; [key: string]: unknown }): string {
  switch (g.type) {
    case 'toxicity-filter':
      return `    # TODO: integrate a toxicity detection library
    # Threshold: ${g.threshold ?? 0.7}
    pass`
    case 'hallucination-detector':
      return `    # TODO: integrate a hallucination detection library (e.g. deepeval)
    pass`
    default:
      return `    # Custom output guardrail: ${g.type}
    pass`
  }
}
