{{- if .Values.controlPlane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentspec-operator.name" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentspec-operator.controlPlaneLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentspec-operator.controlPlaneSelectorLabels" . | nindent 4 }}
{{- end }}
