apiVersion: v1
kind: Service
metadata:
  name: gymcoach-sidecar
  namespace: demo
  labels:
    agentspec.io/agent: gymcoach
    agentspec.io/role: sidecar
spec:
  selector:
    app: gymcoach
  ports:
    - name: control
      port: 4001
      targetPort: control
      protocol: TCP
  type: ClusterIP
